project:
  type: book
  output-dir: docs

book:
  title: "shinylive-in-book-test"
  author: "Max Kuhn"
  chapters:
    - index.qmd
    - generate-data.qmd
    - shiny.qmd


format:
  html:
    theme: cosmo

filters:
  - shinylive

